name: Deploy projeto CRUD

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build project
        run: cd Back && mvn clean install -DskipTests

      - name: Login Docker Hub
        run: docker login -u italojks -p 88498600Ctx

      - name: Build docker image
        run: docker build -t italojks/javadb .
      - name: Push image docker
        run: docker push italojks/javadb

  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      - name: pull image
        run: sudo docker pull italojks/javadb:latest
      - name: run docker container
        run: sudo docker run -d -p 8080:8080 javadb